In [4]:
import numpy as np

old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old.copy()
new[0, :2] = 0

print(old)

[[1 1 1]
 [1 1 1]]


In [7]:
type(lambda x: x+1)

function

In [9]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [30]:
r = np.array(range(36))

In [31]:
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [32]:
r[2:4,2:4]


array([[14, 15],
       [20, 21]])

In [28]:
r.reshape(36)[::7]


array([ 0,  7, 14, 21, 28, 35])